### ISSUE TITLE
Utilize OwnerID for subscribe/unsubscribe commands

### ISSUE THREAD

**Issue by bandicootdancing** [diamondburned/randimg#2]
Took a look and saw this issue https://github.com/diamondburned/arikawa/issues/22
This would be nice to have added to the subscribe/unsubscribe command. Would be even better if it was a role but owner would suffice. Tried adding that myself before making this issue but can't seem to figure out how to properly add it.

**Comment by diamondburned** [comment]
If all you need is an owner ID, just add to before `Subscribe` and `Unsubscribe` this:

```go
if msg.Author.ID != 12312313123132 { // the number should be your user ID
    return nil
}
```

**Comment by bandicootdancing** [comment]
Thanks again for the help. That did the trick with m.Author.ID.
